envs:
  staging:
    - name: to-be-fluxed
      strategy: simple
      trigger: .*/push
      namespace: gimlet-staging
      image: nginx
      tag: '1.17'
      containerPort: '80'
    - name: to-be-fluxed2
      strategy: simple
      trigger: .*/push
      namespace: gimlet-staging
      image: nginx
      tag: '1.17'
      containerPort: '80'